const loremData = `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque sed mi efficitur,interdum turpis vitae, dictum orci.Nullam hendrerit quis erat at lobortis.Ut luctus enim eu euismod tempus.Fusce sit amet hendrerit sapien, sit amet egestas lectus.Ut tincidunt porttitor libero vitae posuere.Ut consectetur laoreet ex ac cursus.Donec nisi libero, auctor eu sem ut, vestibulum sollicitudin nulla.Pellentesque mollis condimentum sem, in vulputate leo vehicula vitae.Vestibulum rhoncus, ex sed suscipit scelerisque, elit est scelerisque nibh,ac iaculis diam dui in dolor. Vestibulum pulvinar pulvinar felis eget faucibus.Praesent at sagittis diam. Lorem ipsum dolor sit amet, consectetur adipiscing elit.Fusce quis metus suscipit, molestie elit vel, imperdiet quam.Fusce eleifend sapien at nibh imperdiet mattis.

    Vivamus id sem finibus, ornare odio nec, maximus purus. Integer quis turpis metus. Etiam feugiat nunc ac viverra mollis. Nulla imperdiet accumsan metus. Etiam scelerisque diam ac dignissim malesuada. Duis mollis orci pharetra, elementum arcu quis, dignissim tortor. Pellentesque pretium luctus tortor, eget finibus magna lobortis eget. Phasellus a porttitor tortor. Phasellus molestie placerat fringilla. Nullam consequat, diam lobortis ultricies varius, lorem odio sagittis lectus, et malesuada diam purus sed eros. Sed eleifend aliquam scelerisque. Sed eget magna vel ipsum elementum eleifend et quis ligula. Nullam euismod vestibulum magna at dignissim. Vestibulum facilisis pellentesque enim, a accumsan enim semper at. Praesent at pharetra erat. Proin consectetur diam sapien, sit amet elementum purus accumsan sed.

    Nunc ligula magna, egestas eget pulvinar finibus, dapibus vel tellus. Proin rutrum fringilla ultricies. Etiam volutpat velit in massa faucibus lobortis. Donec ornare egestas nulla, nec pretium tortor convallis sit amet. Quisque in sapien efficitur, tincidunt lacus eget, ornare eros. Quisque condimentum faucibus sollicitudin. Mauris porttitor magna justo, et vehicula magna interdum nec. Sed congue fringilla ante ac auctor. Nullam imperdiet tempor magna, vel mollis elit faucibus et. Donec luctus sem massa, eu dignissim quam faucibus ac. Integer sit amet hendrerit orci, ut tristique felis. Cras sed sagittis sapien. Nam lacinia odio ac commodo tincidunt. Praesent ac nisi lacus.

    Pellentesque sagittis accumsan dignissim. Maecenas nec accumsan lectus, id scelerisque nulla. Nulla lobortis convallis risus, vitae suscipit ligula facilisis a. Aenean dignissim felis non elit tempor, sit amet ultricies odio dictum. Sed dapibus egestas convallis. Duis imperdiet nec magna at venenatis. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Quisque nec turpis non urna scelerisque rhoncus. Aliquam a rhoncus dui, ut facilisis tortor. Ut neque libero, lacinia non ex ut, euismod sollicitudin quam. Mauris maximus varius lacinia.

    Aliquam ipsum urna, fermentum sit amet quam at, bibendum rutrum arcu. Integer faucibus mauris vitae nisi venenatis, eu ultricies dui aliquam. Curabitur lectus libero, ultrices vitae efficitur sit amet, consequat vel sem. Maecenas vulputate orci magna, at lacinia dolor auctor vel. Quisque nec elementum sem. Pellentesque sit amet mi mi. Pellentesque eu placerat enim. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nullam bibendum ultricies arcu. Integer gravida magna eget blandit sollicitudin. Proin malesuada dignissim nunc eget pharetra. Pellentesque vel varius ligula.`


module.exports.loremIpsumData = loremData;